### ISSUE TITLE
Unable to cast object in Okanshi.OkanshiMonitorRegistry.GetOrAdd

### ISSUE THREAD

**Issue by Yearmix** [mvno/Okanshi#162]
https://github.com/mvno/Okanshi/blob/9029a59968f1c0f488fbb37b7c10b0066d6810fd/src/Okanshi/Registry.fs#L49

Hi Kim,
It seems I have an issue in place 
at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
at Okanshi.OkanshiMonitorRegistry.GetOrAdd[a](MonitorConfig config, Func`2 factory)
that says it cannot convert type that implements ICounter into a type that implements ITimer
Unable to cast object of type 'MyCounter' to type 'MyTimer'. 
Is it possible the method getOrAdd has hash-collision in the hashtable? I'm not good in F# and maybe you have some thoughts

**Comment by olilanz** [comment]
Hi @kichristensen , 
we are working on a fix. Will you be able to do a new release if we get a PR through?
